### ISSUE TITLE
Requires fabric but fabric is installed?

### ISSUE THREAD

**Issue by KweezyCode** [AdvancedXRay/Auto-Clicker#63]
[17:26:43] [main/INFO]: Loading Minecraft 1.21 with Fabric Loader 0.15.11
[17:26:44] [main/WARN]: Mod resolution failed
[17:26:44] [main/INFO]: Immediate reason: [HARD_DEP_NO_CANDIDATE autoclicker-fabric 21.0.1 {depends fabric @ [*]}, ROOT_FORCELOAD_SINGLE autoclicker-fabric 21.0.1]
[17:26:44] [main/INFO]: Reason: [HARD_DEP autoclicker-fabric 21.0.1 {depends fabric @ [*]}]
[17:26:44] [main/INFO]: Fix: add [add:fabric 1 ([(-∞,∞)])], remove [], replace []
[17:26:44] [main/ERROR]: Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Install fabric, any version.
More details:
	 - Mod 'Auto Clicker' (autoclicker-fabric) 21.0.1 requires any version of fabric, which is missing!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.15.11.jar:?]

**Comment by AdyTech99** [comment]
You need to add [Fabric-API](https://modrinth.com/mod/fabric-api)

**Comment by KweezyCode** [comment]
thanks, closing
